module.exports = {
  LAYERS: {
    LAYER_MAP: 0,
    LAYER_FLOOR_DECORE: 10,
    LAYER_FLOOR: 11,
    LAYER_GROUND: 20,
    LAYER_GROUND_PLAYER: 21,
    LAYER_GROUND_PLACEMENT: 29,
    LAYER_AIR: 30,
    UI: 90
  },

  GRID_SIZE: 40,

  KEY_BINDS: {
    ATTACK: 65, // "A"
    MOVE: 77, // "M"
    CAMERA_PAN_LEFT: 37, //LEFT ARROW
    CAMERA_PAN_RIGHT: 39, //RIGHT ARROW
    CAMERA_PAN_UP: 38, //UP ARROW
    CAMERA_PAN_DOWN: 40, //DOWN ARROW
    SHIFT: 16, //SHIFT KEY,
    PLACE_BUILDING: 81, //Q
    MOVE_UP: 87, //W
    MOVE_DOWN: 83, //A
    MOVE_LEFT: 65, //S
    MOVE_RIGHT: 68, //D,
    QUICKSLOT_0: 48,
    QUICKSLOT_1: 49,
    QUICKSLOT_2: 50,
    QUICKSLOT_3: 51,
    QUICKSLOT_4: 52,
    QUICKSLOT_5: 53,
    QUICKSLOT_6: 54,
    QUICKSLOT_7: 55,
    QUICKSLOT_8: 56,
    QUICKSLOT_9: 57
  }
};
