module.exports = {
  LAYER_MAP: 0,
  LAYER_FLOOR: 1,
  LAYER_GROUND: 2,
  LAYER_AIR: 3,

  GRID_SIZE: 40,

  KEY_BINDS: {
    ATTACK: 65, // "A"
    MOVE: 77, // "M"
    CAMERA_PAN_LEFT: 37, //LEFT ARROW
    CAMERA_PAN_RIGHT: 39, //RIGHT ARROW
    CAMERA_PAN_UP: 38, //UP ARROW
    CAMERA_PAN_DOWN: 40, //DOWN ARROW
    SHIFT: 16 //SHIFT KEY
  }
};
