module.exports = {
  LAYER_MAP: 0,
  LAYER_FLOOR: 10,
  LAYER_GROUND: 20,
  LAYER_GROUND_PLACEMENT: 29,
  LAYER_AIR: 30,

  GRID_SIZE: 40,

  KEY_BINDS: {
    ATTACK: 65, // "A"
    MOVE: 77, // "M"
    CAMERA_PAN_LEFT: 37, //LEFT ARROW
    CAMERA_PAN_RIGHT: 39, //RIGHT ARROW
    CAMERA_PAN_UP: 38, //UP ARROW
    CAMERA_PAN_DOWN: 40, //DOWN ARROW
    SHIFT: 16, //SHIFT KEY,
    PLACE_BUILDING: 81, //Q
    MOVE_UP: 87, //W
    MOVE_DOWN: 83, //A
    MOVE_LEFT: 65, //S
    MOVE_RIGHT: 68 //D
  }
};
